- name: System setup
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
      - name: Copy SSH keys
        import_tasks: playbooks/ssh.yml

      - name: Rustup setup
        command: rustup default stable

      - name: Stow dotfiles
        import_tasks: playbooks/dotfiles.yml

      - name: Source env
        command: env
        environment: "{{ env_vars }}"

      - name: Install paru
        import_tasks: playbooks/paru.yml

      - name: System setup
        become: true
        import_tasks: playbooks/system.yml

      - name: Change login manager
        become: true
        import_tasks: playbooks/greetd.yml
