- name: System setup
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Copy SSH keys
      import_tasks: playbooks/ssh.yml

    - name: Rustup setup
      shell: rustup default stable

    - name: Stow dotfiles
      import_tasks: playbooks/dotfiles.yml

    - name: Source env
      shell: source ~/.bash_profile

    - name: Pacman setup
      become: true
      import_tasks: playbooks/pacman.yml

  tasks:
    - name: Install paru
      import_tasks: playbooks/paru.yml

    - name: Install packages
      import_tasks: playbooks/packages.yml

    - name: Install fonts
      import_tasks: playbooks/fonts.yml

    - name: Install AMDGPU drivers
      import_tasks: playbooks/amd-drivers.yml

    - name: System setup
      become: true
      import_tasks: playbooks/system.yml

    - name: Change login manager
      become: true
      import_tasks: playbooks/greetd.yml

    - name: Change theme
      import_tasks: playbooks/theme.yml
