- name: Clone dotfiles
  git:
    repo: "git@github.com:hyperpuncher/dotfiles.git"
    dest: "{{ home }}/dotfiles"
    accept_hostkey: true

- name: Remove bash profile
  shell: rm ~/.bash_profile

- name: Change directory
  shell: cd ~/dotfiles

- name: Stow dotfiles
  shell: "stow -Rv --no-folding {{ item }}"
  loop: "{{ stow_folders }}"
