- name: Clone dotfiles
  git:
    repo: "git@github.com:hyperpuncher/dotfiles.git"
    dest: "{{ home }}/dotfiles"
    accept_hostkey: true

- name: Remove bash profile if exists
  shell: "[ -f ~/.bash_profile ] && rm ~/.bash_profile || true"

- name: Stow dotfiles
  shell: "cd ~/dotfiles && stow -Rv --no-folding {{ item }}"
  loop: "{{ stow_folders }}"
