- name: Install fonts
  community.general.pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-cascadia-code-nerd
      - ttf-jetbrains-mono-nerd
      - ttf-ubuntu-mono-nerd
