- name: Enable greetd
  shell: systemctl enable greetd.service

- name: Change to tuigreet
  lineinfile:
      path: /etc/greetd/config.toml
      regexp: "^command"
      line: command = "tuigreet --window-padding 2 --asterisks --remember --remember-session --time --width 50 --cmd Hyprland"

- name: Change permissions
  shell: chmod -R go+r /etc/greetd

- name: Auto keyring unlock on login
  lineinfile:
      path: /etc/pam.d/greetd
      line: "auth optional pam_gnome_keyring.so"
      insertafter: "auth       include      system-local-login"

- name: Auto keyring unlock on login
  lineinfile:
      path: /etc/pam.d/greetd
      line: "session optional pam_gnome_keyring.so auto_start"
