- name: Install essential packages
  tags: essential
  kewlfft.aur.aur:
    use: paru
    name: "{{ essential }}"

- name: Install packages
  tags: packages
  kewlfft.aur.aur:
    use: paru
    name: "{{ packages }}"
