- name: Clone paru repository
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ home }}/paru"

- name: Change directory to paru
  shell: cd ~/paru

- name: Build and install paru package
  shell: makepkg -si

- name: Cleanup
  shell: cd && rm -r ~/paru
