- name: Clone paru repository
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: "{{ home }}/paru"

- name: Build and install paru package
  shell: cd ~/paru && makepkg -si

- name: Cleanup
  shell: cd && rm -rf ~/paru
