- name: Ensure .ssh directory exists.
  file:
    dest: "{{ home }}/.ssh"
    mode: 0700
    state: directory

- name: Install ssh key
  copy:
    src: ".ssh/id_rsa"
    dest: "{{ home }}/.ssh/id_ed25519"
    mode: 0600

- name: Install ssh key public
  copy:
    src: ".ssh/id_rsa.pub"
    dest: "{{ home }}/.ssh/id_ed25519.pub"
    mode: 0644

- name: Set authorized key took from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ home }}/.ssh/id_ed25519.pub"
  with_fileglob:
    - "{{ home }}/.ssh/*.pub"
