- name: Ensure .ssh directory exists.
  file:
      dest: "{{ home }}/.ssh"
      mode: "0700"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"

- name: Install ssh key
  copy:
      src: ".ssh/id_ed25519"
      dest: "{{ home }}/.ssh/id_ed25519"
      mode: "0600"
      owner: "{{ user }}"
      group: "{{ user }}"

- name: Install ssh key public
  copy:
      src: ".ssh/id_ed25519.pub"
      dest: "{{ home }}/.ssh/id_ed25519.pub"
      mode: "0644"
      owner: "{{ user }}"
      group: "{{ user }}"
